### ISSUE TITLE
Add documentation contribution guidelines

### ISSUE THREAD

**Issue by kowen-rh** [crc-org/crc#141]
We could use guidelines and a set of "rules" for our documentation added to the contribution guidelines.

Things to include:

* Reference materials for markup
* Reference materials for writing modular documentation
* Guidelines around the use of "CodeReady Containers"
    * Example: we cannot use "CRC" as an acronym in our documentation
* Guidelines around our use of attributes
    * Examples:
        * Using the `{bin}` attribute in source blocks
        * Using the `{prod}` attribute

**Comment by gbraad** [comment]
@robin-owen still relevant?

**Comment by robin-owen** [comment]
@gbraad Yes. Honestly, I forgot about this issue. We should add these as soon as reasonably possible. :)

**Comment by rohanKanojia** [comment]
Can we consider this issue closed with https://github.com/crc-org/crc/pull/4490 ?

I see contribution documentation available [here](https://crc.dev/engineering-docs/Developing.html)

**Comment by gbraad** [comment]
This is not relevant anymore.

- The name CodeReady can not be used, except for the remark: "(The Product) Formerly Known As".
- CRC is a valid abbreviation that can be used in the documentation

The reason for this is as follows:
- The documentation has since moved to be maintained under a community model.
- Downstream documentation has been unpublished
- Upstream documentation therefore has been published as http://crc.dev/docs
  - and is referenced from the developer.redhat.com webpages for OpenShift Local
- The extension has to serve as the onboarding and how-to to the use of OpenShift Local
