### ISSUE TITLE
[BUG] [win] Cannot delete crc machines directory, *.vmcx file still in use by another process

### ISSUE THREAD

**Issue by jsliacan** [crc-org/crc#3503]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
nightly
```

### Steps to reproduce

  1. `crc setup` and `crc start`
  2. `crc cleanup`
  3. 
Not 100% reproducible. Sometimes fails tests.

### Expected
Cleanup finished successfully. 

### Actual
![Screenshot from 2023-02-07 15-51-59](https://user-images.githubusercontent.com/2056138/217281121-eae7fd27-6810-4fc6-b932-c089cbfc1e2e.png)

**Comment by gbraad** [comment]
the file is still being used by the vmm. did the VM stop?

**Comment by anjannath** [comment]
often it happens when doing `crc cleanup` directly without `crc stop`. it feels like the vmm is not stopped in time when cleanup proceeds to delete the VM, maybe we have to check in the cleanup code if the VM was stopped successfully before going ahead to delete it.

the cleanup function that is throwing the error:
https://github.com/crc-org/crc/blob/b1b83658d90b7ff43d26b649087cc9e87d92ebcc/pkg/crc/preflight/preflight_checks_windows.go#L155-L172
