### ISSUE TITLE
[BUG] Bundle logic not working as expected for the OKD preset

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3595]
As reported in https://github.com/okd-project/okd/discussions/1556, we see errors like:

```
PS C:\Users\USER> crc config set preset okd
PS C:\Users\USER> crc setup
...
INFO Loading bundle: crc_okd_hyperv_4.12.0-0.okd-2023-02-18-033438_amd64...
Preset okd is used but bundle is provided for openshift preset
```

**Comment by praveenkumar** [comment]
Issue is around https://github.com/crc-org/crc/blob/main/pkg/crc/machine/bundle/metadata.go#L188-L199 logic which return `OpenShift` preset for both `OKD` and `Openshift` side

```golang
func (bundle *CrcBundleInfo) GetBundleType() crcPreset.Preset {
	switch bundle.Type {
	case "snc", "snc_custom":
		return crcPreset.OpenShift
	case "podman", "podman_custom":
		return crcPreset.Podman
	case "microshift", "microshift_custom":
		return crcPreset.Microshift
	default:
		return crcPreset.OpenShift     // <!--- drops here
	}
}
```

and consuming it https://github.com/crc-org/crc/blob/main/pkg/crc/machine/start.go#L915-L920 here so in `start.go` logic need to be change something like below.

```golang
func bundleMismatchWithPreset(preset crcPreset.Preset, bundleMetadata *bundle.CrcBundleInfo) error {
       bundlePreset := bundleMetadata.GetBundleType()
        if preset == crcPreset.OKD && bundlePreset == crcPreset.OpenShift {
               return nil
        }
	if preset != bundleMetadata.GetBundleType() {
		return errors.Errorf("Preset %s is used but bundle is provided for %s preset", preset, bundleMetadata.GetBundleType())
	}
	return nil
}
```

A proper fix would be in the metadata the type should be changed to:
  * `okd` for OKD
  * `snc`/`openshift` for openshift preset.

**Comment by Maurycy-Krzeminski** [comment]
On windows to make OKD work i created my fork with proposed fix:
https://github.com/Maurycy-Krzeminski/crc/commit/609507f062bff21c9ff4adc049ccdbcf2cc269a3
I built it and this was enough for crc to work with OKD bundl
There was no need to change bundleMismatchWithPreset function, i only changed GetBundleType function
After that i had to set kubeadmin-password because there appeared some other problems:
crc config  set  kubeadmin-password ChangeMe
and to access i had to copy kubeconfig from 
C:\Users\USERNAME\\.crc\machines\crc\kubeconfig to 
C:\Users\USERNAME\\.kube\config
And as far as i see everything works

**Comment by praveenkumar** [comment]
@Maurycy-Krzeminski yes this is correct fix, can you put a PR for same?

**Comment by Maurycy-Krzeminski** [comment]
Sure: https://github.com/crc-org/crc/pull/3610

**Comment by praveenkumar** [comment]
Since PR is merged, closing this issue.
