### ISSUE TITLE
[integration-test] disk-resize test failing on openshift CI

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#3771]
Recently (since ~4 sprints back) on the CI disk-resize integration test is failing, it does succeed always upon a retry

**Comment by praveenkumar** [comment]
@anjannath can you put the logs or the link to failled CI job?

**Comment by anjannath** [comment]
yes, here's the link to the logs: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/crc-org_crc/3769/pull-ci-crc-org-crc-main-integration-crc/1684072012844109824

**Comment by praveenkumar** [comment]
As per job history https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-crc-org-crc-main-integration-crc this is not looking good (3 success out of 20 runs). @jsliacan Are you planning to take a look into this?

**Comment by jsliacan** [comment]
Yes yes, I put it on the list in planning yesterday. Although, @praveenkumar not all failures are due to disk-resize. The goproxy sometimes fails due to admin-context login. That way of logging in was a bit unstable even before (we removed it from e2e for this reason IIRC). 

Anyways, I am taking a look at this in the next few days!

**Comment by jsliacan** [comment]
I don't think this is an issue anymore after #3821 went in, let's reopen if the issue re-emerges.
