### ISSUE TITLE
After going through dcoumentation not abel to find answers to a couple of issues

### ISSUE THREAD

**Issue by eliassal** [crc-org/crc#3930]
I am learning Openshift and installed it on a Hyper-V machine. I asked in this forum the following questions, all waht I get  "Please read documentation..."

I did read but still not able to find what I need to know.

At thread https://github.com/crc-org/crc/issues/3925  **access https://console-openshift-console.apps-crc.testing remotely**
The response I got is to visit https://crc.dev/crc/getting_started/getting_started/networking/, which I did which talks only about linux whereas all details I gave indicated that my setup was on Hyper-V.

2nd, I searched the documentation/googles to access the openshift VM called CRC using ssh as follows
 `ssh -i ~/.crc/machines/crc/id_ecdsa core@api.crc.testing`
getting

> ssh: connect to host api.crc.testing port 22: Connection refused

There is no hint in the documentation on how to allow access to port 22 or how to do it!

Why I need to use ssh? Because I am trying to deploy an app and getting the following

> The node was low on resource: ephemeral-storage. Threshold quantity: 4902142351, available: 4652132Ki.

in spite of the fact that I have a lot of space disk on my drive, googled/searched the documentation so not really clear straight forward explanation of the root cause and a fix or any idea on how to solve the issue that is why I wanted to access the VM and see its disk space.

Can somebody help? **And please dont respond again by** "Please read the documentation " and **close the thread.**

Of course documentation should be read which cant be read all when you are trying to setup and want to go a little bit faster than the music. I am working in computers and servers world since 25 years, used github and forums and people editors of a software when asked respond for the specific demande and pointing to the issue if it exists in the documentation.

Thanks for your help

**Comment by gbraad** [comment]
Do NOT file multiple issues in a single one... 👎 This does not help with offering you a consistent answer.

> ssh: connect to host api.crc.testing port 22: Connection refused

On Windows and macOS the VM is hosted with port 2222 as it is based on a userspace networkin stack to allow co-existence with VPN connectivity.

The answer to remote access has been given: https://github.com/crc-org/crc/issues/3925#issuecomment-1825188191. We ONLY offer a setup that works on Linux. For a Windows based setup, using Hyper-V, we can not help you with a solution. This is something you have to figure out yourself, perhaps using a proxy, IIS, etc. This is NOT something we can help with as this is based on your setup. We are a small team and can only provide assistance with what is in the documentation. Since Windows uses a userspace netwpring stack, all is bound on localhost, which differs from the Linux setup. If you want remote setup... use Linux. Most people we deal with have this setup for CI/CD on Linux. Can't help you on Windows.\

> disk space

`crc status` would tell you. About storage, you already have an issue: https://github.com/crc-org/crc/issues/3923 so let's use this to handle the case you enable Monitoring and see issues with PV.

> specific demande and pointing to the issue if it exists in the documentation.

The issue is that you demand an answer from the engineers and sound impatient. We have pointed out the location, and answered what we can offer, and still you want to have more. As said, we do not offer a remote solution on Windows.

**Comment by gbraad** [comment]
> There is no hint in the documentation on how to allow access to port 22 or how to do it!

@praveenkumar @themr0c Something we could consider describing, however the whole topic of userspace/usermode networking has not been described. The last time this was discussed was before Kevin moved teams, which is now over a year and a half? Perhaps we should offer that `crc ssh` command?

**Comment by gbraad** [comment]
> used github and forums and people editors of a software when asked respond for the specific demande and pointing to the issue

I have checked some of your other filed issues and see the same behaviour; demanding answers, filing multiple issues or in different repos, not reading the error message clearly. And this result in the maintainers doing the same: closing the issue, not providing more assistance than needed, etc. Please, read: http://www.catb.org/~esr/faqs/smart-questions.html

_When you ask your question, display the fact that you have done these things first; this will help establish that you're not being a lazy sponge and wasting people's time. Better yet, display what you have learned from doing these things. We like answering questions for people who have demonstrated they can learn from the answers._ - From the 'Before You Ask' section.

**Comment by cfergeau** [comment]
> There is no hint in the documentation on how to allow access to port 22 or how to do it!

This is covered here https://github.com/crc-org/crc/wiki/Debugging-guide

**Comment by gbraad** [comment]
> I am learning Openshift and installed it on a Hyper-V machine. I asked in this forum the following questions, all waht I get "Please read documentation..."

First, this is not a forum but an issue tracker for filling ISSUES. It would have made more sense if you had filed a discussion topic instead. Your learning can probably be better served at:  https://stackoverflow.com/questions/tagged/openshift or any of the other StackExchange related websites at: https://stackexchange.com/search?q=openshift

Second, we are NOT in the business of educating people about the use of OpenShift. For this you have a lot of resources on the internet, such as the aforementioned forum sites, or developer.redhat.com, and others. Please refrain from using our issue tracker as a discussion forum.

**Comment by eliassal** [comment]
Thanks for all of you for your help. @gbraad Ok, I will be patient regarding #3923 and agree to your suggestion.

**Comment by gbraad** [comment]
@cfergeau would it help to mention this difference as part of the generic documentation we have on the portal? It is not something that has come up often, but it is a noticeable difference... or otherwise, since we do not have someone for documentation, we might resolve this as a `crc ssh` command like we had done in Minishift to start a session? However, this was very problematic on Windows as most of the client were non-compliant/faulty.

**Comment by eliassal** [comment]
@gbraad I was able to ssh to the VM uisng the port 2222.

**Comment by gbraad** [comment]
@eliassal Thanks for the report. We usually do not describe this as it is not a very common scenario. Most people do not need to SSH into the VM, as most of the actions can happen from the webconsole. This is why it is part of the debug description.

**Comment by eliassal** [comment]
@gbraad OK great and thanks. So lets concentrate on the issue #3923  as it is my main issue now as almost you responded to all my requests, thanks again. In fact while I was googling for the issue of monitoring I came across a thread where it talked about using commands like df to check space free on drive and I have 12G free space in the VM

**Comment by gbraad** [comment]
some engineers are on PTO, so that issue will not see responses until after next week/next release.
