### ISSUE TITLE
document updated systems requirement for OpenShift 4.15

### ISSUE THREAD

**Issue by themr0c** [crc-org/crc#4031]
Document updated systems requirement for OpenShift 4.15 https://github.com/crc-org/crc/blob/main/docs/modules/getting_started/partials/ref_minimum-system-requirements.adoc

**Comment by themr0c** [comment]
@praveenkumar can you provide details on the new requirements?

**Comment by praveenkumar** [comment]
Due to OVN-K the resource requirement changed and we need to update the default resource for ram to become 10.5 GB instead 9GB. cpu resource going to be same as before.


Following are the metrics of a 4.15 SNO cluster (OVN context).
```
  openshift-ovn-kubernetes                          ovnkube-control-plane-58dd9476d6-wbwjt                        20m (0%)      0 (0%)      320Mi (1%)       0 (0%)         30m
  openshift-ovn-kubernetes                          ovnkube-node-6gdcm                                            80m (1%)      0 (0%)      1630Mi (5%)      0 (0%)         29m
```

And in the case of SDN which CRC still using for 4.14 have following metrics which means in case of CPU, OVN is better but in case of memory it is way too heavy.
```
openshift-sdn                                     sdn-controller-sh2xf                                       20m (0%)      0 (0%)      70Mi (0%)        0 (0%)         46h
openshift-sdn                                     sdn-zv4xr                                                  110m (2%)     0 (0%)      220Mi
```

**Comment by themr0c** [comment]
Should we document: 10.5 GB, or rather 11 GB to stay with full units?
